### ISSUE TITLE
Unable to convert classes into dex format

### ISSUE THREAD

**Issue by prakashangappan** [googleads/googleads-mobile-plugins#102]
Error building Player: CommandInvokationFailure: Unable to convert classes into dex format. See the Console for details.
/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin/java -Xmx2048M -Dcom.android.sdkmanager.toolsdir="/Users/prakash/Library/Android/sdk/tools" -Dfile.encoding=UTF8 -jar "/Applications/Unity/Unity4.6.2p2.app/Contents/BuildTargetTools/AndroidPlayer/sdktools.jar" -

stderr[

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lcom/google/ads/AdSize;
	at com.android.dx.dex.file.ClassDefsSection.add(ClassDefsSection.java:122)
	at com.android.dx.dex.file.DexFile.add(DexFile.java:161)
	at com.android.dx.command.dexer.Main.processClass(Main.java:732)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.processDirectory(ClassPathOpener.java:229)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:158)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at SDKMain.main(SDKMain.java:130)
1 error; aborting
]
stdout[
processing archive bin/classes.jar...
processing com/unity3d/player/a$1.class...
processing com/unity3d/player/a$2.class...
processing com/unity3d/player/a$a.class...
processing com/unity3d/player/a.class...
processing com/unity3d/player/b.class...
processing com/unity3d/player/c$1.class...
processing com/unity3d/player/c$2.class...
processing com/unity3d/player/c.class...
processing com/unity3d/player/d.class...
processing com/unity3d/player/e$1.class...
processing com/unity3d/player/e$2.class...

---------goes on and on.....

We are using unity4.6.2p2, google admob from this http://forum.unity3d.com/threads/free-admob-plugin-simple-prefab.167731/page-2", targeting for android.

Thanks in advance!

**Comment by rampara** [comment]
This is not the right place to get troubleshooting help for a plugin that is not related to the one hosted here. If you would like to try the Google Mobile Ads Unity plugin, it is linked at https://github.com/googleads/googleads-mobile-plugins/releases.

- Ram

**Comment by prakashangappan** [comment]
Hi Ram, 

Thanks for the quick response, sorry for the wrong post here.

I have followed the instructions form this github page, "https://github.com/googleads/googleads-mobile-plugins/tree/master/unity", which was not working. 

When we run it on editor, its showing up all the dummy client function calls properly, but nothing happens on device.

Using, unity 4.6.2p2, targeting for andriod. Here is our admob class,

 using System;
 using UnityEngine;
 using GoogleMobileAds;
 using GoogleMobileAds.Api;
 
 // Example script showing how to invoke the Google Mobile Ads Unity plugin.
 public class GoogleAdMob : MonoBehaviour
 {
     private BannerView bannerView;
 
     void Start()
     {
         RequestBanner ();
     }
     
     private void RequestBanner()
     {
         #if UNITY_EDITOR
         string adUnitId = "unused";
         #elif UNITY_ANDROID
         string adUnitId = "ca-app-pub-xxxxxxxxxxxxxxxxxxxx";
         #elif UNITY_IPHONE
         string adUnitId = "INSERT_IOS_BANNER_AD_UNIT_ID_HERE";
         #else
         string adUnitId = "unexpected_platform";
         #endif
         
         // Create a 320x50 banner at the top of the screen.
         bannerView = new BannerView(adUnitId, AdSize.SmartBanner, AdPosition.Top);
 
         // Load a banner ad.
         bannerView.LoadAd (new AdRequest.Builder ().Build ());
     }
 
     #region Banner callback handlers
     
     public void HandleAdLoaded(object sender, EventArgs args)
     {
         Debug.Log ("HandleAdLoaded event received.");
     }
     
     public void HandleAdFailedToLoad(object sender, AdFailedToLoadEventArgs args)
     {
         Debug.Log ("HandleFailedToReceiveAd event received with message: " + args.Message);
     }
     
     public void HandleAdOpened(object sender, EventArgs args)
     {
         Debug.Log ("HandleAdOpened event received");
     }
     
     void HandleAdClosing(object sender, EventArgs args)
     {
         Debug.Log ("HandleAdClosing event received");
     }
     
     public void HandleAdClosed(object sender, EventArgs args)
     {
         Debug.Log ("HandleAdClosed event received");
     }
     
     public void HandleAdLeftApplication(object sender, EventArgs args)
     {
         Debug.Log ("HandleAdLeftApplication event received");
     }
     
     #endregion
 }

Any help on this? Thanks in advance!

**Comment by rampara** [comment]
Ads will not work when running applications through the Unity editor. You will have to build for Android or iOS.

- Ram

**Comment by rampara** [comment]
Closed to to lack of activity. If this problem still exists, feel free to re-open to issue.

- Ram
